---
- hosts: all
  vars:
    mysql_root_password: "{{ lookup('password', '~/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"
  become: true
  tasks:
  - name: Install MySQL
    apt: name="{{ item }}"
         update_cache=yes
         cache_valid_time=3600
         state=present
    with_items:
      - 'python3-pymysql'
      - 'mysql-server'
  - name: copy cnf
    copy: src=/tmp/.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: Modify configuration file to listen on all interfaces
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^bind-address" line="bind-address=0.0.0.0"
  - name: Find temporary password
    shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
    register: mysql_root_password_temp
    tags: register

  - name: Set new password from temporary password
    shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -u root -p"{{ mysql_root_password_temp.stdout }}"'
  - name: update mysql root password for all root accounts
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 
