- hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Installing nginx
      apt: name=nginx update_cache=yes state=latest
    - name: copy the new nginx welcome file and restart nginx
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
    - name: Starting nginx on boot
      service: name=nginx enabled=yes state=started
