---
- hosts: all
  vars:
    mysql_root_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,hexdigits,punctuation') }}"
  become: true
  tasks:
    - name: Install MySQL
      apt: 
        name:
        - 'python3-pymysql'
        - 'mysql-server'
        - 'mysql-client'
        - 'python3-pymysql'
        update_cache: yes 
        cache_valid_time: 3600 
        state: present
    
    - name: debug root password
      debug:
        var: mysql_root_password
    # Reset root password
    - name: Stop MySQL
      systemd:
        name: mysql
        state: stopped
    - name: set environment variables
      shell: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
    - name: Start MySQL
      systemd:
        name: mysql
        state: started
    - name: Reset root PW
      command: mysql -u root --execute="UPDATE mysql.user SET authentication_string = PASSWORD('{{ mysql_root_password }}') WHERE User = 'root' AND (Host = '{{ ansible_hostname }}' OR Host = '{{ ansible_default_ipv4.address }}' OR Host = 'localhost' OR Host = '127.0.0.1');"
    - name: Flush MySQL privileges
      command: mysql -u root --execute="FLUSH PRIVILEGES"
    - name: Stop MySQL
      systemd:
        name: mysql
        state: stopped
    - name: Unset environment variables
      shell: systemctl unset-environment MYSQLD_OPTS
    - name: Start MySQL
      systemd:
        name: mysql
        state: started 
        enabled: true
    
    #- name: Ensure Anonymous user(s) are not in the database
      #mysql_user: name='' host={{ item }} state=absent
      #with_items:
        #- "{{ ansible_hostname }}"
        #- 127.0.0.1
        #- ::1
        #- localhost
    #- name: Remove the test database
      #mysql_db: name=test state=absent
      #notify:
        #- Restart MySQL

  handlers:
  - name: Restart MySQL
    service:
      name: mysql
      state: restarted
